name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: HYW Page Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - uses: astral-sh/setup-uv@v8.3.2
      - name: Install Python dependencies
        run: uv sync
      - name: Install graphviz
        run: |
          sudo apt update
          sudo apt install -y graphviz
      - name: Page Build
        run: uv run properdocs build -v
      - name: Get Github App Token
        if: ${{ github.event_name == 'push' }}
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Deploy to Github Pages
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          publish_dir: ./site
          cname: hyw.lolic0n.top
